/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eg2;

import com.eg2.dao.EmployeeDAO;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        try
        {
        	EmployeeDAO.getEmployees();
        }catch(Exception e)
        {
        	System.out.println(e);
        }
    }
}
